name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install ./assets/sophon-3.8.0-py3-none-any.whl
        python -m pip install --upgrade pip
        python -m pip install -e '.[dev]'
    # - name: Run linter
    #   run: |
    #     pylint -d all -e E0602 ./fastchat/
    # - name: Check formatting
    #   run: |
    #     black --check .
